import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import postcss from "postcss";
import tailwindcss from "@tailwindcss/postcss";

async function buildTemplateCSS() {
  const templatePath = join(process.cwd(), "src", "templates", "portfolio");
  const inputCSS = `
    @import "tailwindcss";
    @source "${templatePath}/**/*.tsx";
    @source "${templatePath}/**/*.ts";
  `;

  const result = await postcss([tailwindcss()]).process(inputCSS, {
    from: undefined,
  });

  const output = `// Auto-generated by build-template-css.ts. Do not edit.
export const TEMPLATE_CSS = ${JSON.stringify(result.css)};`;

  const outDir = join(process.cwd(), "src", "lib");
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }
  writeFileSync(join(outDir, "template-css.ts"), output, "utf-8");
  console.log(`Template CSS generated: ${result.css.length.toLocaleString()} bytes`);
}

buildTemplateCSS().catch((err) => {
  console.error("Failed to build template CSS:", err);
  process.exit(1);
});
